# Generated by Django 4.2 on 2023-04-16 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_added_by_alter_movie_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='added_by',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
